# Generated by Django 4.0.4 on 2023-12-19 09:56

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=app.models.id_gen, max_length=30, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Done'), (4, 'Rejected')], default=1)),
                ('status_description', models.TextField(default='Your appointment is not yet approved, just wait a few hours before getting approved, thank you.', help_text='Describe the reason for changing the status', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purpose', models.IntegerField(choices=[(1, 'Wedding'), (2, 'Baptism'), (3, 'Funeral')], default=1)),
                ('name_of_husband', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=69, null=True)),
                ('name_of_wife', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True)),
                ('name_of_officer', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True)),
                ('name_of_first_witness', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True)),
                ('name_of_second_witness', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True)),
                ('name_of_third_witness', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True)),
                ('number_of_attendees', models.PositiveIntegerField(default=0)),
                ('husband_birth_certificate', models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates/', validators=[app.models.validate_file_extension])),
                ('wife_birth_certificate', models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates/', validators=[app.models.validate_file_extension])),
                ('child_full_name', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True, verbose_name="Child's Full Name")),
                ('fathers_full_name', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True, verbose_name="Father's Full Name")),
                ('mothers_full_name', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True, verbose_name="Mother's Full Name")),
                ('address', models.CharField(blank=True, default='', help_text='Street, Brgy/Village, City/Town, Province', max_length=50, null=True)),
                ('godparents', models.CharField(blank=True, default='', help_text='Name of God Parents, separated by new line', max_length=1024, null=True)),
                ('child_birth_certificate', models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates/', validators=[app.models.validate_file_extension])),
                ('deceased_full_name', models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True, verbose_name='Deceased Full Name')),
                ('age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_death', models.DateField(default=django.utils.timezone.now)),
                ('place_of_burial_cemetery', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('time_of_burial', models.TimeField(auto_now_add=True)),
                ('first_reader', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('second_reader', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('death_certificate', models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='death_certificates/', validators=[app.models.validate_file_extension])),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=app.models.id_gen, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='ArchivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_file', models.FileField(upload_to='archived_files/')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
            ],
            options={
                'unique_together': {('appointment', 'archived_file')},
            },
        ),
    ]
