# Generated by Django 4.0.4 on 2023-12-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_of_burial',
        ),
    ]
