# Generated by Django 4.0.4 on 2023-12-19 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_time_of_burial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_of_burial',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
